# Generated by Django 4.0.3 on 2022-04-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
