# Generated by Django 4.0.3 on 2022-03-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrentbyuser',
            name='exp_date',
            field=models.DateField(null=True),
        ),
    ]
