# Generated by Django 4.0.3 on 2022-03-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
