# Generated by Django 4.0.3 on 2022-03-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookrentbyuser_exp_date'),
        ('books', '0004_booksmodel_like_count'),
    ]

    operations = [
    ]
