# Generated by Django 4.0.3 on 2022-04-06 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_name', models.CharField(max_length=50)),
                ('store_info', models.TextField()),
                ('store_img', models.CharField(max_length=255)),
                ('store_views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookstore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_store',
            },
        ),
    ]
